#!/usr/bin/python3

def text_indentation(text):
    """
    This function prints a text with 2 new lines after each of these characters: ., ? and :
    If text is not a string. it will raise a TypeError.
    """
    if type(text) != str:
        raise TypeError("text must be a string")
    text = text.strip()
    i = 0
    while i < len(text):
        print(text[i], end='')
        if text[i] in '.?:':
            print('\n')
        i += 1
